version: "3.8"

services:
  


  app:
      build: 
          context: .
      environment:
              - NODE_ENV=production
      volumes: 
          - .:/app
      ports: 
          - 3000:3000
      image: app:react
      container_name: app2
      command: npm start
      stdin_open: true
      restart: always
      
  app-letsencrypt:
        image: linuxserver/letsencrypt
        container_name: app
        ports:
          - 80:80
          - 443:443
        volumes:
          - ./config/letsencrypt:/config
        environment:
          - EMAIL=media@sabertoothtech.in
          - URL=cryptojhinga.com
          #- SUBDOMAINS=www,api
          - VALIDATION=http
          - TZ=Asia/Kolkata
          - PUID=0
          - PGID=0

      
      
      
  
  
  
  
 
